-- MySQL Script generated by MySQL Workbench
-- Sun 10 Apr 2022 01:31:41 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDiP2021x131
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2021x131
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2021x131` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2021x131` ;

-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`tip_korisnika` (
  `tip_korisnika_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tip_korisnika_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`korisnik` (
  `korisnik_id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `korisnicko_ime` VARCHAR(50) NOT NULL,
  `lozinka` VARCHAR(50) NOT NULL,
  `potvrda_lozinke` VARCHAR(50) NOT NULL,
  `lozinka_sha256` CHAR(64) NOT NULL,
  `status_racuna` TINYINT NOT NULL,
  `datum_vrijeme` DATETIME NOT NULL,
  `uvjeti_koristenja` DATETIME NULL,
  `broj_neuspjesne_prijave` INT NULL,
  `tip_korisnika_id` INT NOT NULL,
  PRIMARY KEY (`korisnik_id`),
  INDEX `fk_korisnik_uloga_idx` (`tip_korisnika_id` ASC) ,
  CONSTRAINT `fk_korisnik_uloga`
    FOREIGN KEY (`tip_korisnika_id`)
    REFERENCES `WebDiP2021x131`.`tip_korisnika` (`tip_korisnika_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`drzava` (
  `drzava_id` INT NOT NULL,
  `kontinent` VARCHAR(45) NOT NULL,
  `naziv_drzave` VARCHAR(45) NOT NULL,
  `broj_stanovnika` INT NOT NULL,
  PRIMARY KEY (`drzava_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`dodjeli_moderatora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`dodjeli_moderatora` (
  `drzava_id` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  PRIMARY KEY (`drzava_id`, `korisnik_id`),
  INDEX `fk_dodjeli_moderatora_korisnik1_idx` (`korisnik_id` ASC) ,
  CONSTRAINT `fk_dodjeli_moderatora_drzava1`
    FOREIGN KEY (`drzava_id`)
    REFERENCES `WebDiP2021x131`.`drzava` (`drzava_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dodjeli_moderatora_korisnik1`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2021x131`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`tip_utrke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`tip_utrke` (
  `tip_utrke_id` INT NOT NULL,
  `naziv_utrke` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tip_utrke_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`utrka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`utrka` (
  `utrka_id` INT NOT NULL,
  `tip_utrke_id` INT NOT NULL,
  `opis_utrke` VARCHAR(45) NOT NULL,
  `datum_zavrsetka_prijava` DATETIME NOT NULL,
  `zakljucano` TINYINT NOT NULL,
  `drzava_id` INT NOT NULL,
  PRIMARY KEY (`utrka_id`, `tip_utrke_id`, `drzava_id`),
  INDEX `fk_utrka_tip_utrke1_idx` (`tip_utrke_id` ASC) ,
  INDEX `fk_utrka_drzava1_idx` (`drzava_id` ASC) ,
  CONSTRAINT `fk_utrka_tip_utrke1`
    FOREIGN KEY (`tip_utrke_id`)
    REFERENCES `WebDiP2021x131`.`tip_utrke` (`tip_utrke_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utrka_drzava1`
    FOREIGN KEY (`drzava_id`)
    REFERENCES `WebDiP2021x131`.`drzava` (`drzava_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`etapa` (
  `etapa_id` INT NOT NULL,
  `naziv_etape` VARCHAR(45) NOT NULL,
  `opis_etape` VARCHAR(45) NOT NULL,
  `pocetak_utrke` DATETIME NOT NULL,
  `zakljucano` TINYINT NOT NULL,
  `utrka_id` INT NOT NULL,
  PRIMARY KEY (`etapa_id`, `utrka_id`),
  INDEX `fk_etapa_utrka1_idx` (`utrka_id` ASC) ,
  CONSTRAINT `fk_etapa_utrka1`
    FOREIGN KEY (`utrka_id`)
    REFERENCES `WebDiP2021x131`.`utrka` (`utrka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`bodovno_stanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`bodovno_stanje` (
  `korisnik_id` INT NOT NULL,
  `etapa_id` INT NOT NULL,
  `uspjesno_zavrseno` TINYINT NOT NULL,
  `vrijeme` DATETIME NOT NULL,
  `mjesto` INT NOT NULL,
  `bodovi` VARCHAR(45) NOT NULL,
  INDEX `fk_bodovno_stanje_korisnik1_idx` (`korisnik_id` ASC) ,
  INDEX `fk_bodovno_stanje_etapa1_idx` (`etapa_id` ASC) ,
  CONSTRAINT `fk_bodovno_stanje_korisnik1`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2021x131`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodovno_stanje_etapa1`
    FOREIGN KEY (`etapa_id`)
    REFERENCES `WebDiP2021x131`.`etapa` (`etapa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`prijava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`prijava` (
  `prijava_id` INT NOT NULL,
  `godina_rodenja` DATE NOT NULL,
  `slika_putanja` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `utrka_id` INT NOT NULL,
  PRIMARY KEY (`prijava_id`),
  INDEX `fk_prijava_korisnik1_idx` (`korisnik_id` ASC) ,
  INDEX `fk_prijava_utrka1_idx` (`utrka_id` ASC) ,
  CONSTRAINT `fk_prijava_korisnik1`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2021x131`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prijava_utrka1`
    FOREIGN KEY (`utrka_id`)
    REFERENCES `WebDiP2021x131`.`utrka` (`utrka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`galerija_slika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`galerija_slika` (
  `galerija_id` INT NOT NULL,
  `utrka_id` INT NOT NULL,
  `korisnik_korisnik_id` INT NOT NULL,
  PRIMARY KEY (`galerija_id`, `utrka_id`, `korisnik_korisnik_id`),
  INDEX `fk_galerija_slika_utrka1_idx` (`utrka_id` ASC) ,
  INDEX `fk_galerija_slika_korisnik1_idx` (`korisnik_korisnik_id` ASC) ,
  CONSTRAINT `fk_galerija_slika_utrka1`
    FOREIGN KEY (`utrka_id`)
    REFERENCES `WebDiP2021x131`.`utrka` (`utrka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_galerija_slika_korisnik1`
    FOREIGN KEY (`korisnik_korisnik_id`)
    REFERENCES `WebDiP2021x131`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x131`.`dnevnik_rada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x131`.`dnevnik_rada` (
  `dnevnik_rada_id` INT NOT NULL,
  `datum_vrijeme` DATETIME NOT NULL,
  `upit` VARCHAR(45) NULL,
  `opis_radnje` VARCHAR(200) NULL,
  `korisnik_id` INT NOT NULL,
  PRIMARY KEY (`dnevnik_rada_id`),
  INDEX `fk_dnevnik_rada_korisnik1_idx` (`korisnik_id` ASC) ,
  CONSTRAINT `fk_dnevnik_rada_korisnik1`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2021x131`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
